import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { ScopeParams, standardProfile } from "@dataseed/core";
import { buildBundle, fillForegroundCopy, canonicalJson } from "@dataseed/engine";
import { GENERATOR_VERSION } from "@dataseed/warehouse";
import { salescloudPack } from "../src/index.js";

// ────────────────────────────────────────────────────────────────────────────────────────────────────────
// GOLDEN CORPUS — the byte-for-byte regression gate on the generator.
//
// The corpus warehouse is content-addressed by a cache key that folds in GENERATOR_VERSION. The hazard the
// project has hit repeatedly (see project_seeder_operational_gotchas): you change generation code but FORGET
// to bump GENERATOR_VERSION → the old cached bytes are silently served and a "new" corpus is stale. Tests
// that assert shapes don't catch it; nothing fails until a human eyeballs the data.
//
// This locks the EXACT generated bytes of a fixed (seed, asOf, volume, population, copyMode) corpus into a
// committed snapshot — a hash per object + the GENERATOR_VERSION the snapshot was blessed under. Any change
// to generated bytes (structure OR static copy) flips a hash → this fails. A GENERATOR_VERSION bump flips the
// version line → this fails. Either way you must consciously re-bless.
//
//   ⇒ If this test fails and the change was INTENTIONAL: bump GENERATOR_VERSION in
//     packages/warehouse/src/cache-key.ts, then re-bless with:  pnpm bless:golden
//     (which is just `vitest -u` over this file). Review the snapshot diff in the PR — it is the proof of
//     exactly which objects' bytes moved.
//   ⇒ If this test fails and you did NOT mean to change generation: you have an unintended determinism leak.
// ────────────────────────────────────────────────────────────────────────────────────────────────────────

const GOLDEN_SEED = "golden-corpus-v1"; // FROZEN — changing it re-rolls the whole corpus (don't)
const GOLDEN_ASOF = "2026-01-01T00:00:00.000Z";
const GOLDEN_SCOPE = {
  org: "standard",
  pack: "salescloud",
  volume: 3, // foreground hero deals (exercise the copy fill)
  population: 40, // bulk tier (exercise the combinatorial generator)
  userPoolSize: 8,
  bulkDensity: 0.6,
  scenarioMix: { "at-risk-budget": 34, "healthy-tech": 33, "rfp-gated": 33 },
  seed: GOLDEN_SEED,
};

const sha = (s: string) => createHash("sha256").update(s).digest("hex").slice(0, 16);

describe("GOLDEN corpus — generated bytes are frozen per GENERATOR_VERSION", () => {
  it("hashes every object's payload to a blessed snapshot (re-bless with `pnpm bless:golden` after a deliberate generator change + version bump)", async () => {
    const scope = ScopeParams.parse(GOLDEN_SCOPE);
    const profile = standardProfile(salescloudPack);
    const bundle = buildBundle(scope, profile, salescloudPack, GOLDEN_ASOF);
    await fillForegroundCopy(bundle, "static", GOLDEN_ASOF); // deterministic default fill (the real corpus bytes)

    const objectHashes: Record<string, string> = {};
    let totalRecords = 0;
    for (const obj of [...salescloudPack.objects].sort()) {
      const recs = bundle.records[obj] ?? [];
      if (!recs.length) continue;
      totalRecords += recs.length;
      objectHashes[obj] = `${recs.length}@${sha(canonicalJson(recs))}`; // count + content hash
    }

    // One snapshot object: the version it was blessed under + the per-object byte fingerprint. A drift in
    // EITHER fails the test and forces a conscious re-bless.
    expect({ generatorVersion: GENERATOR_VERSION, totalRecords, objectHashes }).toMatchSnapshot();
  });
});
