// packages/core/src/scope-params.ts
//
// ScopeParams — the GENERIC run parameters the app's Scope Composer produces and
// that drive a generation run. Domain-agnostic: it knows nothing about any one pack.
// The chosen target PACK supplies the scenario vocabulary and interprets the
// generic knobs (e.g. what "volume" means, what scenario names are valid).
//
// One Zod schema = the TS type AND the runtime guard. Invariants encoded here
// (not just documented): scenario-mix percentages sum to 100; volume is a
// positive int (the live record budget clamps it further at plan-time, once a
// CapabilityProfile exists).

import { z } from "zod";

/** Seeding mode: seed inputs and let the target derive (A), direct-seed derived rows (B), or both.
 *  VESTIGIAL: a pre-pivot Mode-A/B distinction from a since-removed intelligence layer. No current pack
 *  reads `ScopeParams.mode`/`BundlePlan.mode` — it's plumbed through but never branched on. Kept (rather
 *  than removed) to avoid a wider contract change; deliberately excluded from the warehouse cache key
 *  (cache-key.ts) since it can't affect generated bytes. */
export const SeedMode = z.enum(["inputs", "derived", "hybrid"]);
export type SeedMode = z.infer<typeof SeedMode>;

/** Salesforce Data Cloud intent: auto-detect from the org, or force on/off. (A platform feature, not a pack
 *  concept.) NOT currently consumed by any pack's generate() (see project_data_cloud_decision.md) — kept for
 *  a future DC sink, deliberately excluded from the warehouse cache key since it can't affect generated bytes. */
export const DcMode = z.enum(["auto", "on", "off"]);
export type DcMode = z.infer<typeof DcMode>;

/** A `--seed` value: a uint32 number, or a memorable string hashed to one (seedFromString). */
export const SeedInput = z.union([z.number().int(), z.string().min(1)]);
export type SeedInput = z.infer<typeof SeedInput>;

/**
 * ScenarioMix — share of generated entities per named scenario. The scenario
 * NAMES belong to the active target pack (e.g. salescloud's deal arcs); core only enforces
 * the structural invariant that the shares sum to 100. Membership is validated at
 * plan-time against the pack's declared scenarios.
 */
export const ScenarioMix = z
  .record(z.string(), z.number().min(0).max(100))
  .refine(
    (mix) => Math.abs(Object.values(mix).reduce((a, b) => a + (b ?? 0), 0) - 100) < 0.001,
    { message: "scenario-mix percentages must sum to 100" },
  );
export type ScenarioMix = z.infer<typeof ScenarioMix>;

export const ScopeParams = z.object({
  /** Target org alias (must already have a CapabilityProfile before generate). */
  org: z.string().min(1),
  /** The target pack id selecting the schema/scenarios to generate (e.g. "salescloud"). */
  pack: z.string().min(1),
  /** Count of primary/top-level FOREGROUND entities (narrative deals) to generate; the pack interprets it. Clamped to the live record budget at plan-time. */
  volume: z.number().int().positive(),
  /**
   * Count of additional BACKGROUND/bulk primary entities (e.g. structural accounts with NO narrative
   * signal streams) generated beyond `volume` to make an org feel populated at scale. The pack
   * interprets it (salescloud: extra Accounts with a realistic opps-per-account distribution but no
   * email/task/transcript copy streams, so they fire no downstream trigger cascade). Default 0 = foreground only
   * (fully backward-compatible). Clamped to the remaining record budget at plan-time.
   */
  population: z.number().int().nonnegative().default(0),
  /**
   * How richly the BULK/population tier is fleshed out across the wider Sales-Cloud object graph
   * (Phase 4E) — 0 = pure structural (Accounts/Contacts/Opps/primary OCR only, the cheapest skeleton),
   * 1 = full (multi-role buying committees + activity timelines + installed-base Assets + support
   * Cases on top of every bulk account). The pack scales each optional family's per-account count by
   * this. At 100K accounts the optional families dominate storage, so this is the lever a scale run
   * dials down. Default 0.6 = a populated-but-affordable org. Has no effect on the foreground tier.
   */
  bulkDensity: z.number().min(0).max(1).default(0.6),
  /**
   * Size of the shared sales-rep User pool that bulk Accounts/Opps/Tasks/Events are distributed across
   * (so a 100K-account org isn't "owned by one user" — the obvious tell, and it unblocks OwnerId-scoped
   * rollups/dashboards downstream). 0 = off (everything owned by the running user,
   * fully backward-compatible). When >0 it's clamped to [1,50] and resolved at plan-time: the pool is
   * suppressed if the org doesn't expose the User object. OwnerId is always a soft lookup, so a
   * license-tight org that can't seat the pool degrades cleanly to running-user ownership.
   */
  userPoolSize: z.number().int().nonnegative().default(0),
  /**
   * The Profile the seeded pool users are created under (a hard `@existing` lookup resolved by Name at
   * load). Default "Standard User" (present in every org class). A license-exhausted Dev org can point
   * this at e.g. "Standard Platform User" without a code change. Only used when userPoolSize > 0.
   */
  userProfileName: z.string().default("Standard User"),
  /** Share of entities per the pack's named scenarios; must sum to 100. */
  scenarioMix: ScenarioMix,
  /** Data Cloud branch; `auto` resolves from the CapabilityProfile. NOT currently read by any pack's
   *  generate() — see the header note on DcMode above. */
  dc: DcMode.default("auto"),
  /** Seed inputs (Mode A), direct-seed derived records (Mode B), or both. NOT currently read by any pack's
   *  generate() — see the header note on SeedMode above. */
  mode: SeedMode.default("inputs"),
  /** Reproducibility root: number or memorable string. */
  seed: SeedInput.default(42),
  /** Hard USD cap on LLM spend for the run (abort-before-overspend). */
  budgetUsd: z.number().nonnegative().default(0),
  /** As-of date anchoring all relative timelines (ISO 8601); injected, never `Date.now()`. */
  asOf: z.string().datetime().optional(),
  /** Pack-specific knobs. Validated by the pack. */
  options: z.record(z.string(), z.unknown()).default({}),
}).strict();
export type ScopeParams = z.infer<typeof ScopeParams>;
