// packages/warehouse/src/cache-key.ts
//
// The corpus is a deterministic PROJECTION of (pack, the byte-determining params, the generator version).
// So a materialized warehouse is a CACHE: re-materializing the same key is a no-op, and any change is a
// clean rebuild. The key must cover EVERY input that changes generated bytes — miss one and the cache
// silently serves stale data (the exact failure a content-hash is meant to prevent).

import { createHash } from "node:crypto";
import { canonicalJson } from "@dataseed/registry";
import type { BundlePlan } from "@dataseed/core";

/**
 * Explicit generator version. Bump this whenever a change to the GENERATION LOGIC (not its inputs)
 * changes output bytes — a new field, a reordered draw, a new bulk family. It is deliberately a hand-set
 * constant, NOT a source-content hash: a hash over a hand-curated file list silently goes stale the day
 * someone adds an input the list forgot, giving false confidence. A visible constant the author bumps is
 * honest — a stale key is a code-review miss, not a silent corruption.
 */
export const GENERATOR_VERSION = "29"; // v2 (P0 realism): bulk Industry coupled to the name's category noun;
// per-deal/per-stream timeline anchors (no asOf-ms leak); unique first+last names within a deal's cast.
// v3: full-name reservation ACROSS foreground deals. v4: reserve first names AND surnames at run level (no
// shared distinctive surname like "Mwangi"/"Becker" across two accounts — v3's full-name key let them recur).
// v5: salescloud pivot — call transcripts emit ContentVersion (Title/PathOnClient/VersionData) instead of
// a custom inbox object; app-specific config/custom objects were dropped from the bundle. Output bytes changed.
// v6: realism variety — foreground anchors SPREAD across distinct industries (no all-Technology cluster);
// variability traits (deal-size band, region) STRATIFIED across foreground units instead of iid (no band cluster).
// v7: self-product cure — copy facts now carry `sells` (the AE's horizontal platform) so the model pitches OUR
// product, not the prospect's own; leaky industry painPhrases recast as internal back-office pains.
// v8: round-2 realism — dossier beats carry settled/open `establishes` facts + `dealState` (monotonic deal
// state, killing re-announced sign-offs + sliding deadlines); per-deal intent-paraphrase variant; defaultMix
// spans all 5 scenarios (no 2-2-2 collapse); run-level AE-name reservation; Veeva grounding de-self-producted.
// v9: OpportunityContactRole.Role derived deterministically from persona — Decision Maker = the Economic
// Buyer/Champion, never the Skeptic/Blocker; IsPrimary = the deal advocate (the OCR now agrees with the prose).
// (v9 also shipped: shared calendar/activity-index + weekdays; fintech grounding de-overlap.)
// v10: round-4 fact-ledger extension — prior closed-won threaded INTO the spine (existing customer frames as
// expansion/renewal + foreground Assets/Cases installed base); pinned scope-count constant (no "5 vs 14
// systems" drift); rfp-gated stages moved mid-funnel; contentKind-locked transcript format. Output bytes changed.
// v11: round-5 (self-product + template-mold) — grounding competitors now the SELLER's rival BI/data vendors
// (not the prospect's own-category rivals) + leaky painPhrases de-self-producted; StageName pinned onto the
// dossier + a stage-maturity ceiling in copy (prose can't run past the record's stage); a per-deal "trigger"
// dimension (consolidation/legacy-migration/failed-inhouse/compliance/post-reorg/cost) varies the why-now so
// the corpus isn't one mold — and the scope-count is surfaced ONLY by the consolidation trigger. Bytes changed.
// v12: round-6 — StageName now DERIVED from deal maturity (EB engaged? budget contested?) so it can't lag the
// prose (one pick per branch → stream-aligned, value changes); OCR no longer tags a "Decision Maker" when the
// cast has no EB/Champion (rfp/early), routing IsPrimary to the most-engaged contact. (Inbound emails also now
// render in the BUYER's voice — copy-layer only, no record bytes.) Bytes changed.
// v13: round-7 (ledger extension + template-mold) — the board/audit DEADLINE and the failed-inhouse BUILD
// DURATION are now pinned canonical quantities in the trigger pain (with a quarter label DERIVED from the
// deadline date), killing the audit's "deadline stated 5 ways" fatal + "build ran 8/18/4 months" drift; a
// per-deal OBJECTION-FOCUS axis (pricing/security/integration/timing/procurement, decorrelated by unitIndex)
// centers each deal's tension differently so two same-scenario deals stop sharing the same objection. Bytes changed.
// v14: single-account protocol (seed-account) — a foreground unit can now draw a FULLY SYNTHETIC LLM-authored
// AccountIdentity (in place of the fixed real-anchor) when one is supplied on the GenerateContext; the synthetic
// account also carries richer firmographics (Type/NumberOfEmployees/AnnualRevenue/Billing*/Description). The
// authored identity is byte-stable via the (seed,index) identity cache (.dataseed/identities) — the same
// determinism contract as the dossier cache. The no-identity (anchor) path is byte-identical to v13.
// v15: bulk-tier realism overhaul (the 100K corpus). Hollow records FILLED — Task/Case now carry varied
// stage-aware Subjects + real Descriptions, CaseComment threads are status-coherent (was 9 bodies/126K).
// Opp.Name DECOUPLED from won/lost state (combinatorial NAME_SHAPES) + standard fields populated
// (Type/LeadSource/Probability/ForecastCategoryName/NextStep) + real OpportunityLineItems (Σ UnitPrice ==
// Amount). Account.Industry drawn INDEPENDENTLY of the name (INDUSTRY_DIST, all 33 values — no more
// Telecom/Education/Banking starvation); Account.Type DERIVED from won-history; Account/Contact standard
// fields populated (Phone/Billing*/Description/Department/LeadSource). Activity dates BOUNDED to each opp's
// open→close window (no post-close pre-sales activity); Assets coherent + tied to a won close. Name/title
// pools widened (300×600 contacts, 4.8M company roots). All NEW draws on derived sub-streams so the
// foreground (anchor + synthetic-identity) paths stay byte-identical to v14.
// v16: bulk-tier MECHANICAL REALISM sweep (residual per-object tells from the v15 audit). (1) Task
// subject↔body now CHANNEL-AGREE — openers partitioned into spoken/written/agnostic sets so an "Email:"
// subject never carries a "Short call, ran late." body. (2) Case is ONE coherent problem: a single
// symptom/subsurface/detail/root-cause (CaseScene) threaded through Subject + Description + the whole
// CaseComment thread (was 3 independent symptom/finding picks); CASE_AREAS components de-articled (kills
// "their the SAML login flow"); closed cases always terminate on a resolution line. (3) Account.Phone +
// Contact.Phone dial code DERIVES from BillingCountry (COUNTRY_DIAL, all 34 GEO countries; was always +1).
// (4) company-names SUFFIXES dropped "GmbH"/"PLC" for country-agnostic "Industries"/"Enterprises" (length
// stays 14 → NAME_SPACE gcd invariant unchanged). (5) Opp.Description now COMBINATORIAL (LEAD×TAIL by
// stage-band/won/lost, splicing product line + department — thousands of variants, was 12). (6) Account
// .Description LEAD×FOCUS×TAIL (was a 5-template Mad-Libs). (7) Events bias to WEEKDAYS (Sat/Sun shifted to
// the nearest weekday, clamped in-window) + business-hour dayparts (~10:00/~14:00, :00/:30, 30/60/90 min)
// and density bumped on late/large deals. (8) Opp {Motion} name token constrained by Type (Existing →
// Renewal/Expansion/Upsell/Cross-Sell/Land&Expand; New → Net-New/Land&Expand — Type decided first). (9)
// Open-pipeline CloseDate horizon widened to ~1–3 quarters with a near-term skew (was br.int(15,150)). (10)
// Installed-base Assets reconcile Price/Quantity/close to a WON deal's License OLI (was a fresh sample). All
// changes are in the BULK tier on derived sub-streams; the foreground (anchor + synthetic-identity) paths
// stay byte-identical to v15.
// v17: BULK DEMAND-GEN FUNNEL — the top-of-funnel that the report-card audit found absent at scale (7 Leads
// / 7 CampaignMembers for a 100K org). (1) A bulk LEAD population: net-new prospects (own company via the
// namer at a reserved index range, no AccountId — Salesforce-correct, parent_ref null), power-law per account,
// full firmographics (Title/Status/Rating/LeadSource/Industry/City/Country). (2) Bulk CAMPAIGNMEMBERS wiring
// the account roster's Contacts AND the new leads onto the campaign set (account-major: parent_ref = the
// contact/lead). (3) The shared CAMPAIGN set scaled 5 → ~30 quarterly + always-on programs over ~3 years
// (buildBulkCampaigns). All on a derived "funnel"/"campaigns" stream; foreground paths byte-identical to v16.
// v18: BULK EAC / ECI ACTIVITY LAYER — the activity-capture + conversation-intelligence SIGNAL at scale (bulk
// EmailMessage was 73 / ContentVersion 19 for a 100K org). The native ECI objects (VoiceCall /
// ConversationParticipant) are NOT createable + ActivityMetric is feature-gated, so the signal is modeled
// through load-safe createable fields. (1) Each bulk Task carries its EAC capture shape — TaskSubtype derived
// from the activity channel (Email/Call/LinkedIn/Cadence), and Call-channel tasks add CallType /
// CallDurationInSeconds / CallDisposition (the ECI telephony fields). (2) A bulk EMAILMESSAGE thread per
// active opp: threaded (shared ThreadIdentifier), alternating inbound(buyer)/outbound(rep) with coherent
// From/To (buyer = a real Contact's email, rep = the account's stable seller address), Status 0/3, dates in
// the opp window, RelatedToId → the Opp. (3) A bulk CONTENTVERSION WebVTT call transcript on a subset of
// late/won opps (speakers = the deal's rep + contacts). New per-account "rep" + derived "email"/"transcript"
// streams; the Task EAC fields draw on the existing "activity" stream. Foreground paths byte-identical to v17.
// v19: STATE/COUNTRY-PICKLIST LOAD-SAFETY (surfaced by the first live load — picklist-enabled orgs reject
// plain-text BillingState/Country). GEO_BY_REGION now carries the ISO countryCode + stateCode AND the
// canonical Salesforce label (resolved against the live dependent BillingStateCode/BillingCountryCode
// picklists). Bulk Account/Contact/Lead emit BOTH the *Code field (validates + autofills on a picklist-on org;
// not-createable → dropped on a picklist-off org) and the canonical label text. State omitted where SF has no
// standard sub-state picklist for the country (UK/DE/FR/…). 3 countries renamed to their SF canonical labels
// (Czech Republic→Czechia, South Korea→Korea Republic of, Hong Kong→Taipei/Taiwan) + their COUNTRY_DIAL keys.
// Also FIXED: TaskSubtype 'Cadence'/'ListEmail' are not API-insertable on a manual Task (→ plain Task).
// v20: EMAIL SUBJECT REALISM (live-corpus audit tell — bulk EmailMessage.Subject was 44 distinct / 226, a
// templated "Kicking off onboarding" ×26 feel). EMAIL_SUBJECT_BY_BAND expanded (≈9/band) and now weaves
// {Account}/{Dept}/{object} tokens (the body's buyer-side topic vocabulary), mixing party/topic/generic
// registers; bulkEmailSubject substitutes a picked {object}/{Object}. Cardinality jumps to hundreds of
// distinct, grounded subjects. Bulk EmailMessage bytes only; foreground unchanged.
// v21: HERO COPY IN THE CORPUS. materialize now FILLS foreground copy (EmailMessage TextBody/Subject, Task
// Description, ContentVersion VersionData) before writeBundle, instead of shipping deferred/blank bodies — so a
// warehouse→org load no longer lands its centerpiece hero deals empty. New plan.copyMode ("static" default —
// deterministic, no API; "claude-code"/"anthropic"/"auto" for VP-grade LLM copy; "none" for blank) is part of
// the corpus identity (folded into the cache key). Foreground body bytes change; bulk unchanged.
// v22: BULK COHERENCE (per the codebase audit). (a) DISJOINT company-name pools — the SUFFIXES pool shared
// five tokens with CATEGORIES (Group/Holdings/Partners/Technologies/Industries), so decode() produced
// "Meadowline Partners Partners" doublings; replaced with category-free corporate forms + a module-load
// disjointness guard (NAME_SPACE M unchanged → all bulk names re-roll). (b) ONE CHAMPION PER DEAL — bulk
// Task/Event/EmailMessage/transcript now route through the opp's PRIMARY contact (≈72% of touches; a minority
// reach another committee member) instead of re-rolling a random contact every interaction; an email thread
// uses one buyer end-to-end, and the call recording's lead speaker is the champion. (c) GROUNDED BODIES —
// bulk email + transcript copy now splices the deal's real Amount (compact $K/$M) + close QUARTER + product
// line: the email opener is always grounded and the transcript carries a grounded rep+buyer turn (voice.md:
// specific = numbers + names + dates). All BULK-tier bytes change; foreground paths byte-identical to v21.
// v23: ATTRIBUTED BUYER QUOTES in bulk Task call-notes. A logged Call now often records what the champion
// actually SAID — a verbatim, attributed, deal-grounded quote ("Dana said \"the $420K is more than we'd
// budgeted — can we phase it.\"") instead of a generic stage statement. Builds directly on v22's one-champion
// routing + grounded facts: the quote is the BUYER's voice, attributed to the deal's primary contact, with
// the real money/quarter/product spliced in. Gated to SPOKEN channels (Call/Voicemail, ~60% of them) so
// written notes stay paraphrase — a name+quote is the highest-fidelity realism beat in a CRM. Bulk Task
// Description bytes change; foreground paths byte-identical to v22.
// v24: ACCOUNT SENTIMENT in the standard Account.Rating field (Hot/Warm/Cold). Every account now carries a
// per-account customer-sentiment label in a REAL standard field (survives the org load; itself realism):
// foreground projects the dossier sentiment SHAPE (accelerating→Hot, stalling→Cold, steady→Warm), bulk
// derives it structurally from won/lost history. Pure projection (no RNG) → ONLY the Account payload changes;
// every other object's bytes are byte-identical to v23. Backs the new MCP `select_accounts` retrieval (query
// accounts by sentiment state + pull their full related-record graph). See packs/salescloud/src/sentiment.ts.
// v25: FOREGROUND STANDARD-FIELD SATURATION (R1, first slice — the hero deals a VP opens were the thinnest
// records, while the bulk tier already saturated ~20 fields/object). The deal record + the org chart are now
// fully fielded: foreground Opportunity (live + the prior win) gains Type/LeadSource/Probability/
// ForecastCategoryName/NextStep/Description — all DERIVED from the pinned stage / priorWin / product line so
// they can't contradict the narrative (Probability/Forecast track the stage; Type is Existing iff the account
// already bought; Description splices the deal's product + the GROUNDED buying department). Foreground Contact
// gains a persona-coherent Department (CFO→Finance, IT-Security→IT) + a funnel LeadSource. Anchor Account gains
// Type (Customer once it has a prior win, else Prospect) — headcount/revenue stay unset for real anchors (the
// deal band would contradict a known public company; synthetic identities still carry full firmographics).
// Geo-coherent billing/phone across the foreground graph is wave 2 (docs/object-audit.md). All NEW draws ride
// derived sub-streams (contactfields/oppfields/priorwin.fields) → the golden diff is FOREGROUND-ONLY (Account +
// Contact + Opportunity move; every bulk-tier object's bytes are byte-identical to v24).
// v26: R1 wave-2 — foreground GEO-COHERENT billing/phone + the org chart. ONE HQ per foreground unit fans out to
// Account billing AND every Contact's mailing/phone (they can never disagree): a real anchor gets its CURATED
// public HQ (anchor-hq.ts — a wrong city for a famous company is a worse tell than a blank; HQ is a public fact,
// not a deal-band-derived size), a synthetic identity honors its authored HQ (ISO codes only when the country is
// known — never fabricated), a divisional clone gets a regional office. Account gains BillingStreet/City/
// PostalCode (ZIP BOUND to the state via a US_STATE_ZIP3 prefix + drawn digits, so a CA address never carries a
// TX ZIP; omitted for non-US) + v19 dual State/Country codes + Phone + AccountSource (+ Ownership for synthetic
// only — never fabricate Public/Private for a real company). Contact gains Phone/MobilePhone/Mailing*. Plus a pure
// Contact.ReportsToId org chart (CFO at top; reports point strictly up-rank → acyclic; a _softRef that drops
// cleanly on the single-batch load — present in the corpus/warehouse/MCP substrate, in-org landing deferred).
// accountFirmographics() no longer authors billing (generate.ts hqGeo is sole author). All new draws ride a
// fresh `geofields` sub-stream → golden diff is FOREGROUND Account + Contact ONLY (Opportunity is the canary —
// it must NOT move; any bulk movement = a leak). Churn→escalated-Case deferred (the golden mix has no
// churning-account unit → untestable). See packs/salescloud/src/anchor-hq.ts + docs/object-audit.md.
// v27: two load-correctness/realism fixes surfaced by a live burn load. (1) FOREGROUND contact emails now
// diacritic-FOLD the name (Engström → engstrom) — a raw `first.last@domain` produced an INVALID_EMAIL_ADDRESS
// on load for accented names (the bulk tier already stripped non-ASCII). (2) BULK-tier BillingPostalCode is now
// bound to the state via US_STATE_ZIP3 (+ drawn digits), same as v26's foreground fix — a random 5-digit ZIP put
// a CA account in a TX ZIP region; omitted for non-US. Both are single-value/1-draw changes on existing streams
// → golden diff is FOREGROUND Contact (only diacritic-named contacts move) + BULK Account (ZIP) only.
// v28: CHURN SIGNAL — the churning-account scenario now emits an ESCALATED support Case grounded in the renewal
// risk (named champion + economic-buyer gate + the landed product + a ~20–75d renewal window), on a fresh
// `churn` sub-stream. It's the health/churn leading indicator that coheres with the account's Cold Rating +
// stalling deal. SCENARIO-gated (not shape-gated) so it can't mis-fire onto a healthy renewal. The golden mix
// has NO churning-account unit, so the golden diff is the VERSION LINE ONLY (every object hash byte-identical) —
// the churn path is covered by a dedicated churning-account scenario test, not the golden fixture.
// v29: FULL-CODEBASE REVIEW FIX BATCH (bugs surfaced by a 61-agent multi-dimension review, each independently
// verified against the live code before fixing). (1) Bulk Opportunity name de-dup indexed the roman-numeral
// suffix by the TOTAL distinct-name count (capped at "VI") instead of a per-base-name collision counter —
// repeat collisions on the same base name rendered the identical literal name 2-4x on one account; now an
// uncapped per-base-name counter. (2) The v28 churn Case's "~N days to the renewal decision" was an
// independent ch.int(20,75) draw that usually contradicted the scenario's real closeInDays window; now derived
// from the live deal's actual CloseDate. (3) Foreground buying-committee titles (PERSONA_DETAIL) were a fixed
// 1:1 persona→title map — every Champion across every demo account was literally "VP, Revenue Operations";
// now a per-persona title POOL sampled per deal. (4) Foreground Task.Priority was hardcoded "Normal" for
// every beat regardless of scenario/sentiment; now derived from the beat's sentiment (Risk/Negative beats can
// draw High). (5) The selling AE's email domain was derived from the PROSPECT's own domain
// ("ae@zscaler-sales.com") — read as impersonation and gave every account a different fictitious vendor; now
// ONE fixed brand domain (SELLER_DOMAIN) across every account, foreground and bulk. (6) The prior-win support
// Case history was a fixed 2-entry subject/description pool — any two prior-win accounts with the same
// caseCount got byte-identical support tickets; now a 5-entry pool, and the foreground closed Case now sets
// ClosedDate (previously always blank, unlike the bulk-tier equivalent). (7) Bulk OpportunityLineItem license
// UnitPrice floored to $1/seat whenever seatCount (headcount-driven) exceeded the license's dollar share,
// overshooting Amount by up to 65%+ once Salesforce recalculates Amount from line items on load; License
// Quantity is now capped to its own dollar share, with any rounding residual absorbed into the last add-on
// line so Σ UnitPrice reconstructs Amount exactly. (8) Foreground anchor assignment could land a deal on
// Snowflake/Confluent/MongoDB — anchors whose own product IS the "horizontal data/analytics/integration
// platform" SELLER_PITCH sells, an uncurable self-product collision; these are now excluded from the
// foreground round-robin pool (still valid anchors elsewhere). (9) The static copy provider's ARC table only
// covered 3 of 5 scenarios — stalled-portfolio/churning-account silently fell back to the upbeat healthy-tech
// arc, producing copy that contradicted the deal's actual declining trajectory; both now have dedicated
// early/mid/late beats. (10) Every ARC beat (email/task/transcript) had exactly ONE phrasing per
// (scenario,phase,direction), so any two beats sharing a phase+direction rendered byte-identical bodies —
// confirmed: a Skeptic and a Champion on the same deal uttering the identical sentence, breaking the
// documented "a CFO and a champion never sound alike" guarantee; every beat field now carries 2 phrasing
// variants picked by a stable per-beat-id hash. Golden diff: every foreground+bulk object that touches
// contact titles/AE email/Task priority/anchor assignment/static copy moves; Campaign/CampaignMember/Event/
// OpportunityContactRole/PricebookEntry/Product2/User/UserRole are unaffected (no fix touched their fields).

/** The plan fields that determine generated bytes — everything the generator reads. asOf IS included
 *  (it anchors every timeline). Excludes derived/display fields (estimatedRecords, perObjectCounts).
 *  `mode`/`withDc` are DELIBERATELY excluded — no pack's generate() currently reads either (see the
 *  header notes on SeedMode/DcMode in scope-params.ts), so folding them in here only bought needless
 *  cache misses: two requests differing ONLY in `mode` or `dc` produce byte-identical records but used
 *  to get different dsIds, defeating the warehouse's whole point of deduping identical corpora. */
function identityParams(plan: BundlePlan): Record<string, unknown> {
  return {
    pack: plan.pack,
    copyMode: plan.copyMode, // foreground copy fill (static/llm/none) determines body bytes → part of identity
    seed: plan.seed,
    asOf: plan.asOf,
    volume: plan.volume,
    population: plan.population,
    bulkDensity: plan.bulkDensity,
    userPoolSize: plan.userPoolSize,
    userProfileName: plan.userProfileName,
    scenarioCounts: plan.scenarioCounts,
    namespacePrefix: plan.namespacePrefix,
  };
}

export interface CorpusKey {
  /**
   * The corpus identity — `ds_<12hex>` of the byte-determining params (INCLUDING asOf, EXCLUDING the
   * generator version). Two corpora with different asOf get DIFFERENT dsIds and coexist; a generator-version
   * bump keeps the same dsId (same logical corpus) so re-materialize rebuilds IN PLACE. NB: this is the
   * warehouse's OWN id — it intentionally differs from the registry's datasetId (which excludes asOf), so
   * distinct-asOf corpora don't collide on one ds_id and silently evict each other.
   */
  dsId: string;
  /** The byte-determining params, hashed — stable across runs with the same inputs. */
  paramsHash: string;
  /** The FULL invalidation key: params + generator version. Re-materialize is a no-op iff this is unchanged. */
  cacheKey: string;
}

/** Compute the content-addressed corpus key for a plan. Pure. */
export function corpusKey(plan: BundlePlan): CorpusKey {
  const paramsHash = createHash("sha256").update(canonicalJson(identityParams(plan))).digest("hex");
  const cacheKey = createHash("sha256").update(paramsHash).update(" ").update(GENERATOR_VERSION).digest("hex").slice(0, 24);
  return { dsId: "ds_" + paramsHash.slice(0, 12), paramsHash, cacheKey };
}
